#pragma once

namespace gamescope {

enum WaylandModifierIndex {
	GAMESCOPE_WAYLAND_MOD_CTRL,
	GAMESCOPE_WAYLAND_MOD_SHIFT,
	GAMESCOPE_WAYLAND_MOD_ALT,
	GAMESCOPE_WAYLAND_MOD_META, // Super
	GAMESCOPE_WAYLAND_MOD_NUM,
	GAMESCOPE_WAYLAND_MOD_CAPS,

	GAMESCOPE_WAYLAND_MOD_COUNT,
};

}
